# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-19 06:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='news',
            options={'verbose_name_plural': 'News'},
        ),
        migrations.RenameField(
            model_name='news',
            old_name='content',
            new_name='article',
        ),
        migrations.RenameField(
            model_name='news',
            old_name='title',
            new_name='headline',
        ),
        migrations.RenameField(
            model_name='news',
            old_name='title_en',
            new_name='headline_en',
        ),
        migrations.RenameField(
            model_name='news',
            old_name='title_ne',
            new_name='headline_ne',
        ),
    ]
