# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-19 06:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_auto_20170619_0615'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='name_en',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='name_ne',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
