# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-19 07:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0005_auto_20170619_0622'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='article_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='news',
            name='article_ne',
            field=models.TextField(null=True),
        ),
    ]
