# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-19 10:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0006_auto_20170619_0700'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='name_en',
        ),
        migrations.RemoveField(
            model_name='category',
            name='name_ne',
        ),
        migrations.RemoveField(
            model_name='news',
            name='article_en',
        ),
        migrations.RemoveField(
            model_name='news',
            name='article_ne',
        ),
        migrations.RemoveField(
            model_name='news',
            name='headline_en',
        ),
        migrations.RemoveField(
            model_name='news',
            name='headline_ne',
        ),
        migrations.RemoveField(
            model_name='news',
            name='reporter_en',
        ),
        migrations.RemoveField(
            model_name='news',
            name='reporter_ne',
        ),
    ]
