# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-20 07:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0009_auto_20170620_0753'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='author',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='news.Author'),
            preserve_default=False,
        ),
    ]
