# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-21 17:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0011_author_photo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='news',
            old_name='publication_date',
            new_name='published_date',
        ),
    ]
