# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-22 10:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0014_auto_20170626_0720'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='slug',
            field=models.SlugField(blank=True, help_text='Leave empty/unchanged for default slug.', max_length=255, null=True),
        ),
    ]
