# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-23 06:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0015_news_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='authors_pictures'),
        ),
    ]
