# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-11-13 06:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0020_auto_20170908_0636'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='source',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
