# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-11-13 07:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0021_news_source'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='published_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
