# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-24 06:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staffmessage',
            name='staff',
        ),
        migrations.DeleteModel(
            name='OfficeStaff',
        ),
        migrations.DeleteModel(
            name='StaffMessage',
        ),
    ]
